# -*- mode: ruby -*-
# vi: set ft=ruby :

$common = <<-SCRIPT
  sudo -u root sh -
  yum -y install container-selinux net-tools telnet sshpass python3
  sed -i 's/ChallengeResponseAuthentication no/ChallengeResponseAuthentication yes/g' /etc/ssh/sshd_config
  systemctl restart sshd.service
SCRIPT

MASTER_BOX_NAME = "my-sexy-homestead-box-master" + "S"
AGENT_BOX_NAME = "my-sexy-homestead-box-agent" + "SW"
MASTER_BOX_IP = "192.168.42.110"
AGENT_BOX_IP = "192.168.42.111"
VM_CPUS = 1
VM_MEMORY = 1024

Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"
  config.vm.box_url = "centos/7"
  config.vm.box_check_update = false
  config.vm.synced_folder '.', '/vagrant', disabled: true

  config.vm.define MASTER_BOX_NAME do |k3s|
    k3s.vm.hostname = MASTER_BOX_NAME
    k3s.vm.network "private_network", ip: MASTER_BOX_IP
    k3s.vm.network "forwarded_port", guest: 6443, host: 6443, host_ip: "0.0.0.0"
    k3s.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id, "--cpus", VM_CPUS]
      vb.customize ["modifyvm", :id, "--memory", VM_MEMORY]
      vb.customize ["modifyvm", :id, "--name", MASTER_BOX_NAME]
    end
    k3s.vm.provision "shell", inline: $common
    k3s.vm.provision "shell", inline: <<-SHELL
      curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--write-kubeconfig-mode 644 server --flannel-iface=eth1" sh -
    SHELL
  end

  config.vm.define AGENT_BOX_NAME do |k3s|
    k3s.vm.hostname = AGENT_BOX_NAME
    k3s.vm.network "private_network", ip: AGENT_BOX_IP
    k3s.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
      vb.customize ["modifyvm", :id, "--cpus", VM_CPUS]
      vb.customize ["modifyvm", :id, "--memory", VM_MEMORY]
      vb.customize ["modifyvm", :id, "--name", AGENT_BOX_NAME]
    end
    k3s.vm.provision "shell", inline: $common
    k3s.vm.provision "shell", inline: <<-SHELL
      echo "Copying NODE_TOKEN ⏳"
      sshpass -p "vagrant" ssh -o StrictHostKeyChecking=no vagrant@192.168.42.110 sudo cat /var/lib/rancher/k3s/server/node-token > ./node-token
      echo "Copy DONE ✅"
      NODE_TOKEN="$(cat node-token)"
      systemctl daemon-reload
      curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--flannel-iface=eth1" K3S_TOKEN=$(echo $NODE_TOKEN) K3S_URL=https://192.168.42.110:6443 sh -
    SHELL
  end

end
