# -*- mode: ruby -*-
# vi: set ft=ruby :

# $script = <<-SCRIPT
#   sudo -u root sh -
#   sh ./scripts/script.sh
# SCRIPT

MASTER_BOX_NAME = "floofi" + "S"
MASTER_BOX_IP = "192.168.42.110"
VM_CPUS = 4
VM_MEMORY = 2048

Vagrant.configure("2") do |config|

	config.vm.box = "centos/7"
	config.vm.box_url = "centos/7"
	config.vm.box_check_update = false
	config.vm.synced_folder '.', '/vagrant', disabled: true

	# config.vm.provision "file", source: "./scripts", destination: "./scripts"
	config.vm.provision "file", source: "./confs", destination: "./confs"

	config.vm.define MASTER_BOX_NAME do |k3s|
		k3s.vm.hostname = MASTER_BOX_NAME
		k3s.vm.network "private_network", ip: MASTER_BOX_IP
		k3s.vm.provider "virtualbox" do |vb|
			vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
			vb.customize ["modifyvm", :id, "--cpus", VM_CPUS]
			vb.customize ["modifyvm", :id, "--memory", VM_MEMORY]
			vb.customize ["modifyvm", :id, "--name", MASTER_BOX_NAME]
		end
		# k3s.vm.provision "shell", inline: $script
	end

end